version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: spring-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: springboot
      MYSQL_DATABASE: spring_database
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: